### ISSUE TITLE
Reed switches details

### ISSUE THREAD

**Issue by adi32k** [juaigl/esphome-garage-cover-single-control#8]
Can you please put some pictures on how you installed the two reed switches on your gate. For the reed switch that is on the other side of the esp module, that in my case is 5 meters apart, do i need to take extra precautions  when i connect it to an esp pin?

**Comment by juaigl** [comment]
Hello

You don't need to put it 5m from the ESP. My gate is 6m long and I have both switches almost side by side.

This is how I did:

![image](https://github.com/juaigl/esphome-garage-cover-single-control/assets/45799632/d3de2aeb-0f82-4f72-9ded-0ee3f62cf750)

**Comment by adi32k** [comment]
> Hello
> 
> You don't need to put it 5m from the ESP. My gate is 6m long and I have both switches almost side by side.
> 
> This is how I did:
> 
> ![image](https://private-user-images.githubusercontent.com/45799632/324174769-d3de2aeb-0f82-4f72-9ded-0ee3f62cf750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTk2NjEsIm5iZiI6MTcxMzc1OTM2MSwicGF0aCI6Ii80NTc5OTYzMi8zMjQxNzQ3NjktZDNkZTJhZWItMGY4Mi00ZjcyLTlkZWQtMGVlM2Y2MmNmNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA0MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOTU5YWZkNDZkMjcyOTcyMWZkNmQxOGRhNzllNmEwMTA1NmUxNmQxZjNhOGQ5M2FkZTQ5Y2MyNTlhY2M3MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OayNwsQUlPjYf74ShMUmSr87xqFLH6U2siPuYpeBFd8)
> 
> 1. Place the reed switches near to you ESP and separated like 10-15 cm one from other
> 2. Fully close the door, place the magnet in the gate in front of close reed switch
> 3. Fully open the door, place the magnet in the gate in front of open reed switch

**Comment by adi32k** [comment]
Thanks
